run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  disable-all: true
  enable:
    # Standard / Default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Quality / Best Practices
    - revive
    - gofmt
    - goimports
    - goconst
    - misspell
    - unparam
    - nakedret
    # Security
    - gosec

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: true
      - name: package-comments
        disabled: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
