// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package db

import (
	"context"
	"database/sql"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs
WHERE
  (
    COALESCE(?, '') = ''
    OR actor LIKE '%' || COALESCE(?, '') || '%'
    OR action LIKE '%' || COALESCE(?, '') || '%'
    OR resource_id LIKE '%' || COALESCE(?, '') || '%'
    OR detail LIKE '%' || COALESCE(?, '') || '%'
  )
  AND (COALESCE(?, '') = '' OR source = COALESCE(?, ''))
  AND (COALESCE(?, '') = '' OR outcome = COALESCE(?, ''))
`

type CountAuditLogsParams struct {
	Column1 interface{}
	Column2 sql.NullString
	Column3 sql.NullString
	Column4 sql.NullString
	Column5 sql.NullString
	Column6 interface{}
	Source  string
	Column8 interface{}
	Outcome string
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLogs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Source,
		arg.Column8,
		arg.Outcome,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (actor, actor_role, source, action, resource_type, resource_id, outcome, detail)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, created_at, actor, actor_role, source, "action", resource_type, resource_id, outcome, detail
`

type CreateAuditLogParams struct {
	Actor        string
	ActorRole    string
	Source       string
	Action       string
	ResourceType string
	ResourceID   string
	Outcome      string
	Detail       string
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, createAuditLog,
		arg.Actor,
		arg.ActorRole,
		arg.Source,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Outcome,
		arg.Detail,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Actor,
		&i.ActorRole,
		&i.Source,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Outcome,
		&i.Detail,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, created_at, actor, actor_role, source, "action", resource_type, resource_id, outcome, detail FROM audit_logs
WHERE
  (
    COALESCE(?, '') = ''
    OR actor LIKE '%' || COALESCE(?, '') || '%'
    OR action LIKE '%' || COALESCE(?, '') || '%'
    OR resource_id LIKE '%' || COALESCE(?, '') || '%'
    OR detail LIKE '%' || COALESCE(?, '') || '%'
  )
  AND (COALESCE(?, '') = '' OR source = COALESCE(?, ''))
  AND (COALESCE(?, '') = '' OR outcome = COALESCE(?, ''))
ORDER BY created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListAuditLogsParams struct {
	Column1 interface{}
	Column2 sql.NullString
	Column3 sql.NullString
	Column4 sql.NullString
	Column5 sql.NullString
	Column6 interface{}
	Source  string
	Column8 interface{}
	Outcome string
	Limit   int64
	Offset  int64
}

// Filters are optional: an empty query string disables the substring match,
// empty source/outcome disable those filters. COALESCE keeps NULL params
// (zero-value sql.NullString) behaving like empty strings, not SQL NULL.
func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Source,
		arg.Column8,
		arg.Outcome,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Actor,
			&i.ActorRole,
			&i.Source,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Outcome,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trimAuditLogs = `-- name: TrimAuditLogs :exec
DELETE FROM audit_logs WHERE id NOT IN (SELECT id FROM audit_logs ORDER BY id DESC LIMIT ?)
`

func (q *Queries) TrimAuditLogs(ctx context.Context, limit int64) error {
	_, err := q.db.ExecContext(ctx, trimAuditLogs, limit)
	return err
}
