// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_events.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countAuthEvents = `-- name: CountAuthEvents :one
SELECT COUNT(*) FROM auth_events
`

func (q *Queries) CountAuthEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuthEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuthEventsByUser = `-- name: CountAuthEventsByUser :one
SELECT COUNT(*) FROM auth_events
WHERE user_id = ?
`

func (q *Queries) CountAuthEventsByUser(ctx context.Context, userID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuthEventsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthEvent = `-- name: CreateAuthEvent :one
INSERT INTO auth_events (user_id, username, event, detail)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, username, event, detail, created_at
`

type CreateAuthEventParams struct {
	UserID   sql.NullInt64
	Username string
	Event    string
	Detail   string
}

func (q *Queries) CreateAuthEvent(ctx context.Context, arg CreateAuthEventParams) (AuthEvent, error) {
	row := q.db.QueryRowContext(ctx, createAuthEvent,
		arg.UserID,
		arg.Username,
		arg.Event,
		arg.Detail,
	)
	var i AuthEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Event,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}

const listAuthEvents = `-- name: ListAuthEvents :many
SELECT id, user_id, username, event, detail, created_at FROM auth_events
ORDER BY created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListAuthEventsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListAuthEvents(ctx context.Context, arg ListAuthEventsParams) ([]AuthEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuthEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthEvent
	for rows.Next() {
		var i AuthEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Event,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthEventsByUser = `-- name: ListAuthEventsByUser :many
SELECT id, user_id, username, event, detail, created_at FROM auth_events
WHERE user_id = ?
ORDER BY created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListAuthEventsByUserParams struct {
	UserID sql.NullInt64
	Limit  int64
	Offset int64
}

func (q *Queries) ListAuthEventsByUser(ctx context.Context, arg ListAuthEventsByUserParams) ([]AuthEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuthEventsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthEvent
	for rows.Next() {
		var i AuthEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Event,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeExpiredAuthEvents = `-- name: PurgeExpiredAuthEvents :exec
DELETE FROM auth_events WHERE created_at < ?
`

func (q *Queries) PurgeExpiredAuthEvents(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.ExecContext(ctx, purgeExpiredAuthEvents, createdAt)
	return err
}
