// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: containers.sql

package db

import (
	"context"
	"strings"
	"time"
)

const deleteOrphanContainers = `-- name: DeleteOrphanContainers :exec
DELETE FROM containers WHERE id NOT IN (/*SLICE:active_ids*/?)
`

func (q *Queries) DeleteOrphanContainers(ctx context.Context, activeIds []string) error {
	query := deleteOrphanContainers
	var queryParams []interface{}
	if len(activeIds) > 0 {
		for _, v := range activeIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:active_ids*/?", strings.Repeat(",?", len(activeIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:active_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getContainer = `-- name: GetContainer :one
SELECT id, name, image, image_id, state, auto_update, update_available, latest_image_digest, last_checked_at, last_updated_at, created_at, updated_at FROM containers WHERE id = ? LIMIT 1
`

func (q *Queries) GetContainer(ctx context.Context, id string) (Container, error) {
	row := q.db.QueryRowContext(ctx, getContainer, id)
	var i Container
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.ImageID,
		&i.State,
		&i.AutoUpdate,
		&i.UpdateAvailable,
		&i.LatestImageDigest,
		&i.LastCheckedAt,
		&i.LastUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUpgradableContainers = `-- name: GetUpgradableContainers :many
SELECT id, name, image, image_id, state, auto_update, update_available, latest_image_digest, last_checked_at, last_updated_at, created_at, updated_at FROM containers 
WHERE auto_update = 1 AND update_available = 1
`

func (q *Queries) GetUpgradableContainers(ctx context.Context) ([]Container, error) {
	rows, err := q.db.QueryContext(ctx, getUpgradableContainers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Container
	for rows.Next() {
		var i Container
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.ImageID,
			&i.State,
			&i.AutoUpdate,
			&i.UpdateAvailable,
			&i.LatestImageDigest,
			&i.LastCheckedAt,
			&i.LastUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContainers = `-- name: ListContainers :many
SELECT id, name, image, image_id, state, auto_update, update_available, latest_image_digest, last_checked_at, last_updated_at, created_at, updated_at FROM containers ORDER BY name ASC
`

func (q *Queries) ListContainers(ctx context.Context) ([]Container, error) {
	rows, err := q.db.QueryContext(ctx, listContainers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Container
	for rows.Next() {
		var i Container
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.ImageID,
			&i.State,
			&i.AutoUpdate,
			&i.UpdateAvailable,
			&i.LatestImageDigest,
			&i.LastCheckedAt,
			&i.LastUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markContainerUpgraded = `-- name: MarkContainerUpgraded :exec
UPDATE containers
SET update_available = 0, last_updated_at = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type MarkContainerUpgradedParams struct {
	LastUpdatedAt interface{}
	ID            string
}

func (q *Queries) MarkContainerUpgraded(ctx context.Context, arg MarkContainerUpgradedParams) error {
	_, err := q.db.ExecContext(ctx, markContainerUpgraded, arg.LastUpdatedAt, arg.ID)
	return err
}

const saveContainer = `-- name: SaveContainer :exec
INSERT INTO containers (
    id, name, image, image_id, state, auto_update, 
    update_available, latest_image_digest, last_checked_at, last_updated_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    image = excluded.image,
    image_id = excluded.image_id,
    state = excluded.state,
    auto_update = excluded.auto_update,
    update_available = excluded.update_available,
    latest_image_digest = excluded.latest_image_digest,
    last_checked_at = excluded.last_checked_at,
    last_updated_at = excluded.last_updated_at,
    updated_at = CURRENT_TIMESTAMP
`

type SaveContainerParams struct {
	ID                string
	Name              string
	Image             string
	ImageID           string
	State             string
	AutoUpdate        int64
	UpdateAvailable   int64
	LatestImageDigest interface{}
	LastCheckedAt     interface{}
	LastUpdatedAt     interface{}
	UpdatedAt         time.Time
}

func (q *Queries) SaveContainer(ctx context.Context, arg SaveContainerParams) error {
	_, err := q.db.ExecContext(ctx, saveContainer,
		arg.ID,
		arg.Name,
		arg.Image,
		arg.ImageID,
		arg.State,
		arg.AutoUpdate,
		arg.UpdateAvailable,
		arg.LatestImageDigest,
		arg.LastCheckedAt,
		arg.LastUpdatedAt,
		arg.UpdatedAt,
	)
	return err
}

const setContainerAutoUpdate = `-- name: SetContainerAutoUpdate :exec
UPDATE containers
SET auto_update = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type SetContainerAutoUpdateParams struct {
	AutoUpdate int64
	ID         string
}

func (q *Queries) SetContainerAutoUpdate(ctx context.Context, arg SetContainerAutoUpdateParams) error {
	_, err := q.db.ExecContext(ctx, setContainerAutoUpdate, arg.AutoUpdate, arg.ID)
	return err
}

const updateContainerUpdateState = `-- name: UpdateContainerUpdateState :exec
UPDATE containers
SET update_available = ?, latest_image_digest = ?, last_checked_at = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateContainerUpdateStateParams struct {
	UpdateAvailable   int64
	LatestImageDigest interface{}
	LastCheckedAt     interface{}
	ID                string
}

func (q *Queries) UpdateContainerUpdateState(ctx context.Context, arg UpdateContainerUpdateStateParams) error {
	_, err := q.db.ExecContext(ctx, updateContainerUpdateState,
		arg.UpdateAvailable,
		arg.LatestImageDigest,
		arg.LastCheckedAt,
		arg.ID,
	)
	return err
}
