// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type AuthEvent struct {
	ID        int64
	UserID    sql.NullInt64
	Username  string
	Event     string
	Detail    string
	CreatedAt time.Time
}

type Container struct {
	ID                string
	Name              string
	Image             string
	ImageID           string
	State             string
	AutoUpdate        int64
	UpdateAvailable   int64
	LatestImageDigest interface{}
	LastCheckedAt     interface{}
	LastUpdatedAt     interface{}
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Session struct {
	SessionID         string
	UserID            int64
	ExpiresAt         time.Time
	CreatedAt         time.Time
	LastSeenAt        time.Time
	AbsoluteExpiresAt time.Time
	UserAgent         string
}

type Setting struct {
	Key       string
	Value     string
	UpdatedAt time.Time
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	Role         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
