// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (session_id, user_id, expires_at)
VALUES (?, ?, ?)
RETURNING session_id, user_id, expires_at, created_at
`

type CreateSessionParams struct {
	SessionID string
	UserID    int64
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.SessionID, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE session_id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, sessionID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT session_id, user_id, expires_at, created_at FROM sessions WHERE session_id = ? LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, sessionID string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, sessionID)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const purgeExpiredSessions = `-- name: PurgeExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < ?
`

func (q *Queries) PurgeExpiredSessions(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, purgeExpiredSessions, expiresAt)
	return err
}
