// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webauthn.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const consumeWebAuthnChallenge = `-- name: ConsumeWebAuthnChallenge :exec
UPDATE webauthn_challenges
SET consumed = 1
WHERE id = ?
`

func (q *Queries) ConsumeWebAuthnChallenge(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, consumeWebAuthnChallenge, id)
	return err
}

const countWebAuthnCredentialsByUser = `-- name: CountWebAuthnCredentialsByUser :one
SELECT COUNT(*) FROM webauthn_credentials
WHERE user_id = ?
`

func (q *Queries) CountWebAuthnCredentialsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWebAuthnCredentialsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebAuthnChallenge = `-- name: CreateWebAuthnChallenge :one
INSERT INTO webauthn_challenges (
    challenge,
    kind,
    user_id,
    expires_at,
    consumed
) VALUES (
    ?, ?, ?, ?, 0
)
RETURNING id, challenge, kind, user_id, expires_at, consumed
`

type CreateWebAuthnChallengeParams struct {
	Challenge []byte
	Kind      string
	UserID    sql.NullInt64
	ExpiresAt time.Time
}

func (q *Queries) CreateWebAuthnChallenge(ctx context.Context, arg CreateWebAuthnChallengeParams) (WebauthnChallenge, error) {
	row := q.db.QueryRowContext(ctx, createWebAuthnChallenge,
		arg.Challenge,
		arg.Kind,
		arg.UserID,
		arg.ExpiresAt,
	)
	var i WebauthnChallenge
	err := row.Scan(
		&i.ID,
		&i.Challenge,
		&i.Kind,
		&i.UserID,
		&i.ExpiresAt,
		&i.Consumed,
	)
	return i, err
}

const createWebAuthnCredential = `-- name: CreateWebAuthnCredential :one
INSERT INTO webauthn_credentials (
    credential_id,
    user_id,
    public_key,
    attestation_type,
    transport,
    aaguid,
    sign_count,
    clone_warning,
    backup_eligible,
    backup_state,
    name,
    created_at,
    last_used_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING credential_id, user_id, public_key, attestation_type, transport, aaguid, sign_count, clone_warning, backup_eligible, backup_state, name, created_at, last_used_at
`

type CreateWebAuthnCredentialParams struct {
	CredentialID    []byte
	UserID          int64
	PublicKey       []byte
	AttestationType string
	Transport       string
	Aaguid          []byte
	SignCount       int64
	CloneWarning    int64
	BackupEligible  int64
	BackupState     int64
	Name            string
	CreatedAt       time.Time
	LastUsedAt      sql.NullTime
}

func (q *Queries) CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) (WebauthnCredential, error) {
	row := q.db.QueryRowContext(ctx, createWebAuthnCredential,
		arg.CredentialID,
		arg.UserID,
		arg.PublicKey,
		arg.AttestationType,
		arg.Transport,
		arg.Aaguid,
		arg.SignCount,
		arg.CloneWarning,
		arg.BackupEligible,
		arg.BackupState,
		arg.Name,
		arg.CreatedAt,
		arg.LastUsedAt,
	)
	var i WebauthnCredential
	err := row.Scan(
		&i.CredentialID,
		&i.UserID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Transport,
		&i.Aaguid,
		&i.SignCount,
		&i.CloneWarning,
		&i.BackupEligible,
		&i.BackupState,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteWebAuthnCredential = `-- name: DeleteWebAuthnCredential :execrows
DELETE FROM webauthn_credentials
WHERE credential_id = ? AND user_id = ?
`

type DeleteWebAuthnCredentialParams struct {
	CredentialID []byte
	UserID       int64
}

func (q *Queries) DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWebAuthnCredential, arg.CredentialID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUnconsumedWebAuthnChallenge = `-- name: GetUnconsumedWebAuthnChallenge :one
SELECT id, challenge, kind, user_id, expires_at, consumed FROM webauthn_challenges
WHERE challenge = ? AND kind = ? AND consumed = 0 AND expires_at > ?
LIMIT 1
`

type GetUnconsumedWebAuthnChallengeParams struct {
	Challenge []byte
	Kind      string
	ExpiresAt time.Time
}

func (q *Queries) GetUnconsumedWebAuthnChallenge(ctx context.Context, arg GetUnconsumedWebAuthnChallengeParams) (WebauthnChallenge, error) {
	row := q.db.QueryRowContext(ctx, getUnconsumedWebAuthnChallenge, arg.Challenge, arg.Kind, arg.ExpiresAt)
	var i WebauthnChallenge
	err := row.Scan(
		&i.ID,
		&i.Challenge,
		&i.Kind,
		&i.UserID,
		&i.ExpiresAt,
		&i.Consumed,
	)
	return i, err
}

const getWebAuthnCredential = `-- name: GetWebAuthnCredential :one
SELECT credential_id, user_id, public_key, attestation_type, transport, aaguid, sign_count, clone_warning, backup_eligible, backup_state, name, created_at, last_used_at FROM webauthn_credentials
WHERE credential_id = ? LIMIT 1
`

func (q *Queries) GetWebAuthnCredential(ctx context.Context, credentialID []byte) (WebauthnCredential, error) {
	row := q.db.QueryRowContext(ctx, getWebAuthnCredential, credentialID)
	var i WebauthnCredential
	err := row.Scan(
		&i.CredentialID,
		&i.UserID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Transport,
		&i.Aaguid,
		&i.SignCount,
		&i.CloneWarning,
		&i.BackupEligible,
		&i.BackupState,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listWebAuthnCredentialsByUser = `-- name: ListWebAuthnCredentialsByUser :many
SELECT credential_id, user_id, public_key, attestation_type, transport, aaguid, sign_count, clone_warning, backup_eligible, backup_state, name, created_at, last_used_at FROM webauthn_credentials
WHERE user_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListWebAuthnCredentialsByUser(ctx context.Context, userID int64) ([]WebauthnCredential, error) {
	rows, err := q.db.QueryContext(ctx, listWebAuthnCredentialsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebauthnCredential
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.CredentialID,
			&i.UserID,
			&i.PublicKey,
			&i.AttestationType,
			&i.Transport,
			&i.Aaguid,
			&i.SignCount,
			&i.CloneWarning,
			&i.BackupEligible,
			&i.BackupState,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeExpiredWebAuthnChallenges = `-- name: PurgeExpiredWebAuthnChallenges :exec
DELETE FROM webauthn_challenges
WHERE expires_at < ? OR consumed = 1
`

func (q *Queries) PurgeExpiredWebAuthnChallenges(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, purgeExpiredWebAuthnChallenges, expiresAt)
	return err
}

const renameWebAuthnCredential = `-- name: RenameWebAuthnCredential :execrows
UPDATE webauthn_credentials
SET name = ?
WHERE credential_id = ? AND user_id = ?
`

type RenameWebAuthnCredentialParams struct {
	Name         string
	CredentialID []byte
	UserID       int64
}

func (q *Queries) RenameWebAuthnCredential(ctx context.Context, arg RenameWebAuthnCredentialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renameWebAuthnCredential, arg.Name, arg.CredentialID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWebAuthnCredentialUsage = `-- name: UpdateWebAuthnCredentialUsage :exec
UPDATE webauthn_credentials
SET sign_count = ?,
    last_used_at = ?,
    backup_state = ?,
    clone_warning = ?
WHERE credential_id = ?
`

type UpdateWebAuthnCredentialUsageParams struct {
	SignCount    int64
	LastUsedAt   sql.NullTime
	BackupState  int64
	CloneWarning int64
	CredentialID []byte
}

func (q *Queries) UpdateWebAuthnCredentialUsage(ctx context.Context, arg UpdateWebAuthnCredentialUsageParams) error {
	_, err := q.db.ExecContext(ctx, updateWebAuthnCredentialUsage,
		arg.SignCount,
		arg.LastUsedAt,
		arg.BackupState,
		arg.CloneWarning,
		arg.CredentialID,
	)
	return err
}
